version: '2.2'
services:
  web:
    build: .
    ports:
      - "6832:5000"
    cpus: 0.1
    mem_limit: 128M
    restart: on-failure
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    cpus: 0.1
    mem_limit: 128M
    restart: on-failure
